---
title: "Global warming evidences in New York city"
date: "April 19, 2015"
output:
  html_document:
    theme: cerulean
    fig_caption: yes

---

<!-- For more info on RMarkdown see http://rmarkdown.rstudio.com/ -->

<!-- Enter the code required to load your data in the space below. The data will be loaded but the line of code won't show up in your write up (echo=FALSE) in order to save space-->
```{r echo=FALSE}

```

<!-- In the remainder of the document, add R code chunks as needed -->

### Introduction:

Global warming is a current concern everywere in the world. Greenhouse gases, such as carbon dioxide, methane and ozone resulting from industrial activities and fossil fuel burning (diesel oil and gasoline) by automobiles cause the *greenhouse effect* and are among the major causes for this warming.

The average temperature increases resulting from global warming can usually be observed over long periods of time, such as decades or even a century. It is usually hard to find significant evidences of warming from one year to the next, for example.

The present research aims to find statistical evidence of the global warming effects over the city of New York (USA), based on the temperature records of the NOAA (National Climatic Data Center) of the climatic station located in the Central Park area (Belvedere Tower - Latitude 40.77889° / Longitude -73.96917° / Elevation 39.6 m) from December 21, 1876 to December 20, 2014.

One may believe that the average temperature increases are more noticiable in specific seasons of the year. Crossing the NOAA temperature data with the *timeanddate.com* seasons calculator, this research will try to address this possibility.

Finally, it is possible to state the research questions to be answered :

* Had the average temperature of New York city actually increased over the last 138 years, from 1876 to 2014 ?
* Is the average temperature increase more noticiable in one of the seasons of the year, or basically the same ?

It is probably redundant to deeply discuss the relevance of the global warming question in the modern world. The global warming is impacting the quality of life of almost all the humankind, creating negative climatic effects such as storms, tornadoes, expansion of subtropical deserts, unstable rain periods, heat waves, droughts, heavy snows, etc. Additionally, a huge part of the global warming effect is absorbed by the oceans, increasing significantly their average temperature and generating melted ice in the arctic regions, which consequently rises the sea levels and threatens the cities in the seashore.

### Data:

The New York Central Park station is able to colect several diferent climatic variables, such as air temperature, wind, precipitation (rain and snow), sunshine index, etc. For this research, the only interesting variable is related to the air temperature. 

Originally, the data provided by NOAA database gives the the minimum and maximum temperatures for each recorded day, in tenths of degrees Celcius. For the purpose of this research, the average temperature between the daily minimum and maximum was calculated.

In order to allow the investigation of the possible influence of the seasons of the year, a variable called *season* was created based on the exact dates of the climatic solstices and equinoxes which define the end of a season and the start of the next, according to *timeanddate.com* seasons calculator.

Finally, as the effect of the increase of average temperature is usually more evident after longer periods of time, the available data was split in six distinct periods of 23 years each, as follows :

* *Period 1 :* years of 1877 to 1899
* *Period 2 :* years of 1900 to 1922
* *Period 3 :* years of 1923 to 1945
* *Period 4 :* years of 1946 to 1968
* *Period 5 :* years of 1969 to 1991
* *Period 6 :* years of 1992 to 2014

The help in this identification, a variable called *period* was also created.

In the 

### Exploratory data analysis:

Insert exploratory data analysis here...

### Inference:

Insert inference section here...

### Conclusion:

Insert conclusion here...

### References:

* Wikipedia - Global Warming (viewed on April 18, 2015) (http://en.wikipedia.org/wiki/Global_warming)
* NOAA - National Climatic Data Center (data retrieved on April 14, 2015) (https://gis.ncdc.noaa.gov/map/viewer/#app=cdo)
* Timeanddate.com - Solstices & Equinoxes for New York (data retrieved on April 14, 2015) (http://www.timeanddate.com/calendar/seasons.html)
